/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CategorySchema extends BaseModel {
  static $columns = ['archivedAt', 'color', 'createdAt', 'id', 'name', 'type', 'updatedAt', 'userId'] as const
  $columns = CategorySchema.$columns
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class InviteSchema extends BaseModel {
  static $columns = ['acceptedAt', 'createdAt', 'email', 'expiresAt', 'fullName', 'id', 'tokenHash', 'updatedAt'] as const
  $columns = InviteSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RecurringInstanceSchema extends BaseModel {
  static $columns = ['amount', 'confirmedAt', 'createdAt', 'id', 'periodMonth', 'recurringRuleId', 'transactionId', 'updatedAt', 'userId'] as const
  $columns = RecurringInstanceSchema.$columns
  @column()
  declare amount: number
  @column.dateTime()
  declare confirmedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.date()
  declare periodMonth: DateTime
  @column()
  declare recurringRuleId: string
  @column()
  declare transactionId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class RecurringRuleSchema extends BaseModel {
  static $columns = ['amount', 'archivedAt', 'categoryId', 'createdAt', 'dayOfMonth', 'id', 'installmentsTotal', 'kind', 'name', 'startMonth', 'type', 'updatedAt', 'userId'] as const
  $columns = RecurringRuleSchema.$columns
  @column()
  declare amount: number
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare categoryId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dayOfMonth: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare installmentsTotal: number | null
  @column()
  declare kind: string
  @column()
  declare name: string
  @column.date()
  declare startMonth: DateTime
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class TransactionSchema extends BaseModel {
  static $columns = ['amount', 'categoryId', 'createdAt', 'date', 'description', 'id', 'type', 'updatedAt', 'userId'] as const
  $columns = TransactionSchema.$columns
  @column()
  declare amount: number
  @column()
  declare categoryId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
